version: '3.8'

services:
  postgres-db:
    image: postgres:15.3-alpine3.18
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data

  web:
    build: ./
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    depends_on:
      - postgres-db
    ports:
      - 3000:3000
    volumes:
      - .:/app